version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - STRINGEE_API_KEY_SID=${STRINGEE_API_KEY_SID}
      - STRINGEE_API_KEY_SECRET=${STRINGEE_API_KEY_SECRET}
      - STRINGEE_SMS_FROM=${STRINGEE_SMS_FROM}
      - STRINGEE_CALL_FROM=${STRINGEE_CALL_FROM}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env.production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
